### PR TITLE
Add telegram data

### LINKED ISSUE #170: Add telgram auth information
Add a colum to login table with the users telegram id

### PR DESCRIPTION
**Pull request by axel1200**
Fixes #170 
Would be nice if I could get a quick review that would allow me to test api changes on the test server.

### CODE REVIEW

**Comment by axel1200** [comment]
What if we decide to make double verification possible or we decide to not allow telegram anymore this modle would provide more flexibility.

**Comment by micheljung** [comment]
I would prefer if we keep verification methods separate and if a user can have multiple verifications. If it was for me, I'd even display those in the user's profile.

**Downlord**
:heavy_check_mark: Verified by steam account
:heavy_check_mark: Verified by Telegram Passport
:heavy_check_mark: Well-known community member
:x: Verified by phone number

So I would work toward a flexible solution. Something like a generic table `account_verification` mc:1 `login` which has a enum-column `verification_type` and some value field(s) where we can enter telegram passport ID, steam ID, a mobile phone number's etc. either as hashed value or in plain, depending on what the requirements and/or use cases are.

This way we could support N verification methods while avoiding specialized columns and tables, making it easy to add or remove methods.

**Comment by axel1200** [comment]
So I would need to change python server for this will somebody help me?

**Comment by axel1200** [comment]
@Brutus5000 @micheljung how should i handle the steam id. Shell i still save which account has which steam id? or shall i go for hashing them all? And if yes have one table for all hashed authorization ids in one table.

**Comment by axel1200** [comment]
I think @Brutus5000 idea was not not link any hashes or ids(form steam or telegram) to the user so they would need a separate table.

**Comment by axel1200** [comment]
Look at the changes a made that is what i thought of

**Comment by axel1200** [comment]
Would be nice if u rereviewed

**Comment by axel1200** [comment]
Yeah I know I read that.

**Comment by Geosearchef** [comment]
The plan was to consider adding UID OR Telegram (letting users choose) on top of Steam linking.

**Comment by Brutus5000** [comment]
No it was not. This was definitely not common consensus.

**Comment by axel1200** [comment]
@Geosearchef That is what most devs had in mind. But visonik was a different opinion on that.

**Comment by axel1200** [comment]
why that ? Steam is more than sufficent

**Comment by Brutus5000** [comment]
Telegram was an alternative solution to people who don't want to link steam for whatever reason. Goal: increase the potential playerbase (unification of the sets).
Adding telegram on top gives us an even smaller playerbase (the intersection of people who want to link to steam and use Telegram).

**Comment by Geosearchef** [comment]
That's what people suggested during the debate in #general.

**Comment by visionik** [comment]
For clarification, it's fine to add additional 'verification' methods if the community or devs want.  My point was just that we need to require steam link account verification and most importantly verification they own sc:fa via steam.  Another way of thinking about it is via Downlords comment above that users could have multiple verifications, I'm just saying steam link + game verify is the only mandatory verification.

**Comment by axel1200** [comment]
Well i think neither geo nor i are in favor of making even stricter rules I think our goal was to stop decreasing number of ppl logging into faf, because we enforce steam link(Which you can clearly see in statistics we collect). The reason we enforced steam link was that we want to stop trolls like feather or super not that we wanted to verify the ppl own the game on steam. At least that was the reason @Rackover made the server PR from what I know. So geo and I thought of different mechanism on how to stop feather, super and co. What would be to telegram link or to make the UID system stricter. But steam link is more than sufficient for that. I find it sad we want to keep steam link  enforced but if that is legally necessary so it be.

**Pull request closed without merging**
