### PR TITLE
Login data: test user passwords now get correctly hashed

### PR DESCRIPTION
**Pull request by Brutus5000**
Changed the insert statements to SHA2(..., 256) the test-passwords.

### CODE REVIEW

**Comment by Sheeo** [comment]
This is going to break the server tests here: https://github.com/FAForever/server/blob/develop/tests/integration_tests/test_server.py#L80

I wouldn't mind a PR to SHA-256 encode the passwords there as well ;)

**Comment by IDragonfire** [comment]
Does the server tests not using this?
https://github.com/FAForever/server/blob/develop/tests/data/db-fixtures.sql

**Comment by Brutus5000** [comment]
I think Sheeo commented the wrong PR. I am working on his suggestion anyway. ;-)

**Comment by IDragonfire** [comment]
maybe, link to correct pr:
https://github.com/FAForever/server/pull/134

**Comment by Sheeo** [comment]
Indeed, I commented on the wrong PR :)

**Pull request merged**
