### PR TITLE
Changing achievement statistics view to table

### PR DESCRIPTION
**Pull request by norraxx**

### CODE REVIEW

**Review by bukajsytlos — COMMENTED** [review]
lgtm although not sure if 1 min is enough

**Comment by norraxx** [comment]
It's more than enough, it will happen only once per whole server, shouldn't create load.
It's global user statistics count.

**Comment by Askaholic** [comment]
What are achievement_statistics even used for? Just to know how many people have unlocked which achievements?

**Comment by norraxx** [comment]
What I know, user profile -> statistics, and from chat -> right click on user -> profile -> statistics.

**Review by bukajsytlos — APPROVED** [review]

**Comment by Brutus5000** [comment]
In the API the statistics are joined into the achievement entity (https://api.faforever.com/data/achievement).

That's also the reason why the server got overloaded when we started pushing achievements. Each time the lobby server pushes (at least once per second) the API loads the achievement and performs the statistics view query which takes 2s on a server with minimum load. (and went up to 60 seconds under heavy load)

**Review by Brutus5000 — APPROVED** [review]

**Pull request merged**
