### PR TITLE
#194 faf-java-api speed up achievement_statistics view

### PR DESCRIPTION
**Pull request by norraxx**
Achievments take long to load

### CODE REVIEW

**Comment by Brutus5000** [comment]
-- DO NOT MERGE --
Slightly modified test run on production shows that it is slower than the old view.
Needs further investigation.

**Comment by norraxx** [comment]
I'm ok with that.

How about to leave just one index, that might relieve DB during query?
I'll check if it does so, ofcourse.
```
ALTER TABLE `player_achievements`
ADD INDEX `state_player_id_achievement_id_update_time` (`state`, `achievement_id`,  `player_id`, `update_time`);
```

**Comment by Brutus5000** [comment]
How do we want to proceed with this PR? As our tests on the test server indicate the new indices itself speed up the query a bit, but the new query itself is not fast than the old one.

**Comment by axel1200** [comment]
We fixed it right?

**Comment by micheljung** [comment]
Closing due to inactivity

**Pull request closed without merging**
