### PR TITLE
Feat/clan

### PR DESCRIPTION
**Pull request by IDragonfire**
Migrate clan schema into faf schema ...

### CODE REVIEW

**Comment by Sheeo** [comment]
Is this all that's required?

**Comment by IDragonfire** [comment]
Atm yes, I plan to use for invitation the crypto way ;)
I want also to make it as simple as possible.

Did you miss something?

**Comment by Sheeo** [comment]
No, I'm fine with the required set of tables being small :) Can you rebase onto latest tip?

**Comment by IDragonfire** [comment]
rebased + force pushed

**Comment by micheljung** [comment]
was this meant to be closed unmerged, @Sheeo ?

**Comment by Sheeo** [comment]
It was merged with https://github.com/FAForever/db/commit/51fae516ca771597201c3c51e081f583a8bfdcef.

**Comment by IDragonfire** [comment]
Thanks ;)

**Pull request closed without merging**
